apikey: sendgrid
test_defaults:
  to: ivan.bueno@jud.ca.gov
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: trialcourt@courtinfo.ca.gov
  to_name: ''
  reply_to: trialcourt@courtinfo.ca.gov
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
