display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        admin_title:
          label: 'Título administrativo'
        file__target_id:
          label: Ubicación
          separator: ', '
        operations:
          label: Operaciones
  block_1:
    display_title: Bloque
