display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      arguments:
        field_specific_visibility_target_id:
          exception:
            title: Todo(s)
      use_more_text: más
  block_1:
    display_options:
      arguments:
        field_specific_visibility_target_id:
          exception:
            title: Todo(s)
  page_1:
    display_title: Página
