display:
  default:
    display_title: MÃ¡ster
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
  block_1:
    display_options:
      arguments:
        nid:
          exception:
            title: Todo(s)
