_core:
  default_config_hash: zu1yG13sSQJcXrOJJqsn33W_hUWAIFHVlphrzxT2ycV
page_title: Sitemap
message:
  format: plain_text
  value: ''
plugins:
  menu:
    main:
      enabled: true
include_css: true
