label: Glosario
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      title: Glosario
      arguments:
        name:
          exception:
            title: Todo(s)
  attachment_1:
    display_title: Adjunto
    display_options:
      arguments:
        name:
          exception:
            title: Todo(s)
  page_1:
    display_title: Página
