features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://jcart_banner_sigblock.png'
favicon:
  use_default: true
facebook: ''
twitter: ''
youtube: ''
hide_translation: 1
header_extended: 1
mega_menu: 1
footer_extended: 0
footer_extended_message: ''
color_inverted: 0
site_entity_type: ''
