features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://learning_repo_logo.png'
favicon:
  use_default: true
facebook: ''
twitter: ''
youtube: ''
hide_translation: 1
