name: 'Juvenile CART'
mail: no-reply@courtinfo.ca.gov
slogan: 'Juvenile Cases, Articles, Resources, Trainings'
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: 39xtgXrOgWf5RNUvb1GEpd2NaWLBt_9KL4Ue2DG3NJk
uuid: b50ede9b-6817-4146-a079-b4f4eda06725
