_core:
  default_config_hash: BP55XPOfnavpw1nspUjrOmau7ZkxMxMVJ5_B-ybJYCs
enabled: false
required_roles:
  authenticated: authenticated
  administrator: administrator
  editor: '0'
  author: '0'
send_plugins: {  }
login_plugins: {  }
allowed_validation_plugins:
  ga_login_totp: ga_login_totp
default_validation_plugin: ga_login_totp
validation_plugin_settings:
  ga_login_totp:
    time_skew: 2
    site_name_prefix: 1
    name_prefix: TFA
    issuer: Drupal
  ga_login_hotp:
    counter_window: 10
    site_name_prefix: 1
    name_prefix: TFA
    issuer: Drupal
  tfa_recovery_code:
    recovery_codes_amount: 10
validation_skip: 3
encryption: tfa
tfa_flood_uid_only: 1
tfa_flood_window: 300
tfa_flood_threshold: 6
help_text: 'Contact support to reset your access'
mail:
  tfa_enabled_configuration:
    subject: 'Your [site:name] account now has two-factor authentication'
    body: "[user:display-name],\r\n\r\nThanks for configuring two-factor authentication on your [site:name] account!\r\n\r\nThis additional level of security will help to ensure that only you are able to log in to your account.\r\n\r\nIf you ever lose the device you configured, you should act quickly to delete its association with this account.\r\n\r\n--\r\n[site:name] team"
  tfa_disabled_configuration:
    subject: 'Your [site:name] account no longer has two-factor authentication'
    body: "[user:display-name],\r\n\r\nTwo-factor authentication has been disabled on your [site:name] account.\r\n\r\nIf you did not take this action, please contact a site administrator immediately.\r\n\r\n--\r\n[site:name] team"
trust_cookie_expiration: 2592000
cookie_name: TFA
fallback_plugins:
  tfa_totp:
    tfa_recovery_code:
      enable: 1
      settings:
        recovery_codes_amount: 9
      weight: -2
  tfa_hotp:
    tfa_recovery_code:
      enable: 1
      settings:
        recovery_codes_amount: 9
      weight: -2
