ignored_config_entities:
  - openid_connect.settings.windows_aad
  - geocoder.geocoder_provider.bingmaps
  - 'google_tag.container.*'
  - google_tag.settings
  - system.site
  - block.block.jccglossifypathexclusion
  - block.block.jccbooknavigationblock
  - jcc_components.settings.logo
  - jcc_components.settings.facebook
  - jcc_components.settings.twitter
  - jcc_components.settings.youtube
  - jcc_components.settings.scheme
  - jcc_components.settings.email
  - jcc_components.settings.flickr
  - jcc_components.settings.linkedin
  - jcc_components.settings.rss
  - jcc_components.settings.header_footer_variant
  - jcc_components.settings.site_name_first
  - jcc_components.settings.site_name_second
  - jcc_components.settings.hat_shoe_title
  - jcc_components.settings.hat_shoe_url
  - jcc_components.settings.hat_shoe_text
  - 'jcc_components.settings:hide_translation'
  - 'jcc_components.settings:show_google_translate'
  - 'key.key.*'
  - 'xmlsitemap.xmlsitemap.*'
  - 'webform.webform.*'
  - ~webform.webform.was_this_helpful
_core:
  default_config_hash: qiWsOz-1fNonGbUHX9LhplgRG2G9jaHSI46wbXCjytw
