check:
  disabled_extensions: false
  interval_days: 1
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - jcc@example.com
  threshold: all
_core:
  default_config_hash: qfPRXS0PpSa5AijSfo0HQfhpG3h9EqVTTwr_JCdqn1E
