_core:
  default_config_hash: 5G_b8LoI7ejYxSxBnNTsYebGk0EjseT_h23d1BZZBKY
messaging_content_types:
  custom_email: custom_email
  alert: 0
  document: 0
  importer: 0
  judge: 0
  landing_page: 0
  location: 0
  news: 0
  subpage: 0
  tentative_ruling: 0
messaging_display_footer_form: 0
