features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: sites/merced/logo.svg
favicon:
  use_default: true
scheme: local
header_footer_variant: default
site_name_first: 'Superior Court of California'
site_name_second: 'County of Merced'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://merced.courts.ca.gov'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_translation: 1
show_google_translate: 0
