_core:
  default_config_hash: w1F6gmM_hfR7_7r1dXLiPCxGdjQWOxM4ABrefOp08-E
ignored_config_entities:
  - 'jcc_*.settings'
  - openid_connect.settings.windows_aad
  - geocoder.geocoder_provider.bingmaps
  - geocoder.geocoder_provider.openrouteservice
  - 'google_tag.container.*'
  - google_tag.settings
  - system.site
  - extlink.settings
  - block.block.jccglossifypathexclusion
  - block.block.jccbooknavigationblock
  - webform_myemma.settings
  - jcc_subscriptions.settings
  - 'key.key.*'
  - xmlsitemap.settings.yml
  - 'xmlsitemap.xmlsitemap.*.yml'
  - block.block.relatednews
