ignored_config_entities:
  - 'jcc_*.settings'
  - openid_connect.settings.windows_aad
  - geocoder.geocoder_provider.bingmaps
  - system.site
  - extlink.settings
  - block.block.jccglossifypathexclusion
  - block.block.jccbooknavigationblock
  - key.key.newsroom_sendgrid
  - social_post_twitter.settings
_core:
  default_config_hash: w1F6gmM_hfR7_7r1dXLiPCxGdjQWOxM4ABrefOp08-E
