_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  access_unpublished: 0
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  advagg: 0
  anchor_link: 0
  autocomplete_deluxe: 0
  automated_cron: 0
  better_exposed_filters: 0
  better_social_sharing_buttons: 0
  block: 0
  block_content: 0
  block_field: 0
  book: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor_a11ychecker: 0
  ckeditor_balloonpanel: 0
  ckeditor_templates: 0
  ckeditor_templates_ui: 0
  color: 0
  colorbox: 0
  colorbox_inline: 0
  comment: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  config_update: 0
  contact: 0
  content_lock: 0
  content_lock_timeout: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  email_registration: 0
  embed: 0
  encrypt: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_facet_link: 0
  entity_reference_revisions: 0
  entity_usage: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  facets: 0
  facets_summary: 0
  features: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  focal_point: 0
  formblock: 0
  fullcalendar_view: 0
  ga_login: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geolocation: 0
  geolocation_leaflet: 0
  glossify: 0
  glossify_taxonomy: 0
  google_tag: 0
  hierarchical_term_formatter: 0
  honeypot: 0
  hook_post_action: 0
  image: 0
  image_widget_crop: 0
  imagemagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  insert_view_adv: 0
  jcc_autocomplete_duplicates: 0
  jcc_block_field_decorator: 0
  jcc_blocks: 0
  jcc_book_navigation: 0
  jcc_ckeditor: 0
  jcc_embed_generator: 0
  jcc_featured_links: 0
  jcc_feeds_file_proxy: 0
  jcc_glossify_path_exclude: 0
  jcc_ical: 0
  jcc_media_formatter: 0
  jcc_migrate_source_ui: 0
  jcc_newslinks: 0
  jcc_node_edit: 0
  jcc_subscriptions: 0
  jcc_tc_announcement: 0
  jcc_tc_block_paragraph_: 0
  jcc_tc_book: 0
  jcc_tc_configuration: 0
  jcc_tc_content_moderation: 0
  jcc_tc_content_paragraph_: 0
  jcc_tc_custom: 0
  jcc_tc_document: 0
  jcc_tc_event: 0
  jcc_tc_faq: 0
  jcc_tc_feeds: 0
  jcc_tc_field_storage: 0
  jcc_tc_job: 0
  jcc_tc_landing_page: 0
  jcc_tc_links: 0
  jcc_tc_location: 0
  jcc_tc_migration: 0
  jcc_tc_news: 0
  jcc_tc_page: 0
  jcc_tc_person: 0
  jcc_tc_taxonomy_base: 0
  jcc_tc_tours: 0
  jcc_video_embed_granicus: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  json_feed: 0
  key: 0
  language: 0
  libraries: 0
  link: 0
  link_attributes: 0
  linkit: 0
  locale: 0
  login_emailusername: 0
  mailsystem: 0
  maxlength: 0
  media: 0
  media_directories: 0
  media_directories_editor: 0
  media_directories_ui: 0
  media_library: 0
  media_library_form_element: 0
  menu_item_extras: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  migrate: 0
  migrate_file: 0
  migrate_google_sheets: 0
  migrate_plus: 0
  migrate_process_inline_images: 0
  migrate_source_csv: 0
  migrate_tools: 0
  moderated_content_bulk_publish: 0
  module_filter: 0
  mysql: 0
  node: 0
  office_hours: 0
  openid_connect: 0
  openid_connect_windows_aad: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  path: 0
  path_alias: 0
  queue_ui: 0
  rdf: 0
  real_aes: 0
  redirect: 0
  redis: 0
  regex_redirect: 0
  responsive_image: 0
  robotstxt: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search_api: 0
  search_api_attachments: 0
  search_api_autocomplete: 0
  search_api_pantheon: 0
  search_api_pantheon_admin: 0
  search_api_solr: 0
  search_api_sorts: 0
  selective_better_exposed_filters: 0
  sendgrid_integration: 0
  sitemap: 0
  social_api: 0
  social_post: 0
  sophron: 0
  straw: 0
  svg_formatter: 0
  svg_image: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  term_reference_tree: 0
  text: 0
  tfa: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_daterange_filters: 0
  views_entity_form_field: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  webform: 0
  webform_myemma: 0
  webform_ui: 0
  weight: 0
  workflows: 0
  extlink: 1
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  jcc_tc: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  jcc_base: 0
  jcc_newsroom: 0
profile: jcc_tc
