features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
  path: 'public://NewsroomDrupalBanner Blue.png'
favicon:
  use_default: true
facebook: ''
twitter: 'https://twitter.com/CalCourts'
youtube: 'https://www.youtube.com/user/CaliforniaCourts'
hide_translation: 1
email: 'https://newsroom.courts.ca.gov/alerts'
flickr: 'https://www.flickr.com/photos/californiacourts/sets/'
linkedin: 'https://www.linkedin.com/company/judicial-council-of-california/'
rss: 'https://newsroom.courts.ca.gov/rss'
site_entity_type: ''
header_extended: 1
mega_menu: 0
footer_extended: 1
footer_extended_message: ''
color_inverted: 0
