apikey: newsroom_sendgrig_test
test_defaults:
  to: baptiste.niviere@gmail.com
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: 'Newsroom test'
  to_name: Baptiste
  reply_to: ''
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
