favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: sites/sf/logo.svg
  use_default: false
scheme: local
header_footer_variant: default
site_name_first: 'Superior Court of California'
site_name_second: 'County of San Francisco'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: 'https://twitter.com/SFSuperiorCourt'
youtube: ''
hide_translation: 1
show_google_translate: 1
