features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
scheme: base
header_footer_variant: default
site_name_first: 'California Courts'
site_name_second: 'Courts of Appeal'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov/'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_translation: 0
hide_was_this_helpful: 1
