features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
favicon:
  use_default: true
scheme: base
header_footer_variant: default
site_name_first: 'California Judicial Branch'
site_name_second: 'Design System'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_translation: 0
