features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
scheme: base
header_footer_variant: default
site_name_first: 'California Courts'
site_name_second: 'Judicial Branch of California'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov'
email: 'https://newsroom.courts.ca.gov/'
facebook: ''
flickr: 'https://www.flickr.com/photos/californiacourts/albums/'
linkedin: 'https://www.linkedin.com/company/judicial-council-of-california/posts/?feedView=all'
rss: ''
twitter: 'https://x.com/CalCourts'
youtube: 'https://www.youtube.com/user/CaliforniaCourts'
hide_translation: 0
header_body:
  value: ''
  format: full_html
hide_was_this_helpful: 1
show_google_translate: 0
no_search_results_heading: 'We are unable to find a result for you.'
no_search_results_message:
  value: "<p>Please try again with a different keyword or here are some resources that can help answer common questions:</p>\r\n\r\n<ul>\r\n\t<li>See the <a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"82c2bdfb-1aa7-4bfb-a6cf-811abe2f7882\" href=\"/node/32509\">Homepage</a> for more options</li>\r\n\t<li>Find&nbsp;<a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"34c5d4a2-a4af-4ab1-99b0-57340f719179\" href=\"/node/9\">Rules &amp; Forms</a></li>\r\n\t<li>Review&nbsp;<a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"b0c03a13-65d5-4371-9b43-fb2398349c36\" href=\"/node/10\">Opinions</a></li>\r\n\t<li>Self-represented litigants can find information on legal matters by visiting the <a href=\"https://selfhelp.courts.ca.gov/\">Self Help Guide</a>, including content in different languages</li>\r\n</ul>\r\n"
  format: snippet
news_default_seal: themes/custom/jcc_elevated/images/news-default-seal.svg
block_search_engine_indexing: 0
landing_advisory_body: /node/2942
landing_course: ''
landing_event: ''
landing_facilities: /node/12482
landing_job: /node/33055
landing_judge: ''
landing_location: ''
landing_news: ''
landing_opinion_citings_archive: ''
landing_opinion_published: /node/12324
landing_opinion_published_extended: /node/25086
landing_opinion_published_review_granted: /node/31921
landing_opinion_unpublished: /node/12325
landing_opinion_unpublished_review_granted: /node/31922
landing_publication: ''
landing_request: /node/16340
landing_surplus_materials: ''
