features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
scheme: base
header_footer_variant: default
site_name_first: 'California Courts'
site_name_second: 'Judicial Branch of California'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_translation: 0
header_body:
  value: ''
  format: full_html
hide_was_this_helpful: 1
show_google_translate: 0
no_search_results_heading: ''
no_search_results_message:
  value: ''
  format: snippet
news_default_seal: 'themes/custom/jcc_elevated/images/news-default-seal.svg'  
