#uuid: ab68cb48-4ba2-4e0f-a6bf-a9fbad1edb7a
langcode: en
status: true
dependencies: {  }
id: media_legislative_report_update
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - courts_phase3
  - media
migration_group: courts_phase3
label: 'Media Update - Legislative reports'
source:
  plugin: csv
  path: 'public://media_update.csv'
  header_row_count: 1
  ids:
    - url 
  fields:    
    -
      name: title
      selector: title
      label: Title
    -
      name: url
      selector: url
      label: Url
    -
      name: year
      selector: year
      label: Year
    -
      name: topic
      selector: topic
      label: Topic
    -
      name: office
      selector: office
      label: Office
    -
      name: budget_funding
      selector: budget_funding
      label: Budget Funding
    -
      name: category
      selector: category
      label: Category

process:  
  mid:
    -
      plugin: media_id_lookup
      source: url
    -
      plugin: skip_on_empty
      method: row
  field_category:
    #-
    #  plugin: default_value
    #  default_value: 'Legislative Reports'
    -
      plugin: entity_generate
      source: category
      entity_type: taxonomy_term
      bundle_key: vid
      bundle: media_file_category      
      value_key: name
      ignore_case: true
  field_source:
    - 
      plugin: entity_generate
      source: budget_funding
      entity_type: taxonomy_term
      bundle_key: vid
      bundle: source
      value_key: name
      ignore_case: true        
  field_matters_served:
    - 
      plugin: entity_generate
      source: topic
      entity_type: taxonomy_term
      bundle_key: vid
      bundle: matters_served
      value_key: name
      ignore_case: true    
  field_tags:  
    - 
      plugin: entity_generate
      source: office
      entity_type: taxonomy_term
      bundle_key: vid
      bundle: media_tags
      value_key: name
      ignore_case: true   
  field_date:
    -
      plugin: format_date
      source: year
      from_format: m/d/Y
      to_format: 'Y-m-d' 
destination:
  plugin: 'entity:media'
  update_only: true
  key: mid
  skip_file_fields: true
  no_stub: true
  validate: false
  overwrite_properties:
    - field_category
    - field_matters_served
    - field_tags
    - field_date
    - field_source
migration_dependencies:
  required: {  }