#uuid: ab68cb48-4ba2-4e0f-a6bf-a9fbad1edb7a
langcode: en
status: true
dependencies: {  }
id: media_budget_funding_allocations_update
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - courts_phase3
  - media
migration_group: courts_phase3
label: 'Media Update - Budget Funding Allocations'
source:
  plugin: csv
  path: 'public://budget_allocations.csv'
  header_row_count: 1
  ids:
    - url 
  fields:    
    -
      name: title
      selector: title
      label: Title
    -
      name: url
      selector: url
      label: Url
    -
      name: year
      selector: year
      label: Year
    -
      name: topic
      selector: topic
      label: Topic
    -
      name: office
      selector: office
      label: Office
    -
      name: funding
      selector: funding
      label: Funding
    -
      name: category
      selector: category
      label: Category
  constants:
    dot: .    
    public: 'public://'
    slash: /
process:
  pseudo_filename:
  -
    plugin: callback
    callable: pathinfo
    source: url
  -
    plugin: extract
    index:
      - filename
  -
    plugin: service
    service: transliteration
    method: transliterate
  -
    plugin: service
    service: pathauto.alias_cleaner
    method: cleanstring    
  pseudo_extension:
  -
    plugin: callback
    callable: pathinfo
    source: url
  -
    plugin: extract
    index:
      - extension  
  pseudo_subfolder:
  -
    plugin: callback
    callable: pathinfo
    source: url
  -
    plugin: extract
    index:
      - dirname
  - 
    plugin: explode
    delimiter: '/'   
  -
    plugin: array_pop   
  pseudo_filename_full:
  -
    plugin: concat
    source:
      - constants/public
      - '@pseudo_subfolder'
      - constants/slash
      - '@pseudo_filename'
      - constants/dot
      - '@pseudo_extension'  
  mid:
    -
      plugin: media_id_lookup
      source: '@pseudo_filename_full'
    -
      plugin: skip_on_empty
      method: row
  field_category:
    -
      plugin: entity_generate
      source: category
      entity_type: taxonomy_term
      bundle_key: vid
      bundle: media_file_category      
      value_key: name
      ignore_case: true
  field_source:
    - 
      plugin: entity_generate
      source: funding
      entity_type: taxonomy_term
      bundle_key: vid
      bundle: source
      value_key: name
      ignore_case: true        
  field_matters_served:
    - 
      plugin: entity_generate
      source: topic
      entity_type: taxonomy_term
      bundle_key: vid
      bundle: matters_served
      value_key: name
      ignore_case: true    
  field_tags:  
    - 
      plugin: entity_generate
      source: office
      entity_type: taxonomy_term
      bundle_key: vid
      bundle: media_tags
      value_key: name
      ignore_case: true   
  field_date:
    -
      plugin: format_date
      source: year
      from_format: m/d/Y
      to_format: 'Y-m-d' 
  field_media_text/value: title        
destination:
  plugin: 'entity:media'
  update_only: true
  key: mid
  skip_file_fields: true
  no_stub: true
  validate: false
  overwrite_properties:
    - field_category
    - field_matters_served
    - field_tags
    - field_date
    - field_source
    - field_media_text
migration_dependencies:
  required: {  }