display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        filename:
          separator: ', '
  page_2:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        type:
          label: 'Entity type'
      arguments:
        fid:
          exception:
            title: All
