display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        name:
          separator: ', '
        description__value:
          separator: ', '
      arguments:
        name:
          exception:
            title: All
  attachment_1:
    display_options:
      arguments:
        name:
          exception:
            title: All
  page_1:
    display_title: Page
