display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      fields:
        name:
          separator: ', '
        link:
          label: Operations
  page:
    display_title: Page
