_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    ru: ru
    fil: fil
    zh-hans: zh-hans
    zh-hant: zh-hant
    pt-br: pt-br
    pt-pt: pt-pt
  domains:
    en: ''
    es: ''
    ru: ''
    fil: ''
    zh-hans: ''
    zh-hant: ''
    pt-br: ''
    pt-pt: ''
selected_langcode: site_default
