features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: sites/imperial/logo.svg
favicon:
  use_default: true
scheme: local
header_footer_variant: default
site_name_first: 'Superior Court of California'
site_name_second: 'County of Imperial'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov'
email: ''
facebook: 'https://www.facebook.com/ImperialSupeCrt/'
flickr: ''
linkedin: 'https://www.linkedin.com/company/imperialsuperiorcourt/'
rss: ''
twitter: 'https://twitter.com/ImperialSupeCrt'
youtube: ''
hide_translation: 0
show_google_translate: 0
