icons_path: libraries/courtyard-artifact/2.x/source/_patterns/01-atoms/icon/icons.svg
_core:
  default_config_hash: YEpMoU49oC871PiWRosPf4I4Jx8Z5DPqpoC5HZzVvWA
icon_sets: "fa\r\nline-white\r\nline-dark"
