_core:
  default_config_hash: SmvBk92BEAUiEXDQEmBvuH0fRx-BmSLB3Y7_eqNPH-A
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: sites/inyo/logo.svg
  use_default: false
facebook: 'https://www.facebook.com/CaliforniaCourts/'
twitter: 'https://twitter.com/CalCourts'
youtube: 'https://www.youtube.com/californiacourts'
scheme: local
email: ''
flickr: ''
linkedin: ''
rss: ''
hide_translation: 0
header_extended: 0
mega_menu: 0
footer_extended: 0
footer_extended_message: ''
color_inverted: 0
header_footer_variant: default
site_name_first: 'Superior Court of California'
site_name_second: 'County of Inyo'
hat_shoe_title: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov'
hat_shoe_text: 'Judicial Branch of California'
show_google_translate: 0
