enabled: false
settings:
  client_id: null
  client_secret: null
  authorization_endpoint: 'https://example.com/oauth2/authorize'
  token_endpoint: 'https://example.com/oauth2/token'
  userinfo_endpoint: 'https://example.com/oauth2/UserInfo'
_core:
  default_config_hash: 8BMhOaiarGVMqVjHaGrKi6K16o4FZX9ixCcF4u8AgYA
