_core:
  default_config_hash: 39xtgXrOgWf5RNUvb1GEpd2NaWLBt_9KL4Ue2DG3NJk
langcode: en
uuid: 373cdb8c-887d-4dc5-93ba-c4b665bf512a
name: 'Superior Court of California | County of Inyo'
mail: no-reply@courtinfo.ca.gov
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
