enabled: windows_aad
settings:
  redirect_url: ''
  client_id: null
  client_secret: null
  authorization_endpoint_wa: null
  token_endpoint_wa: null
  userinfo_endpoint_wa: null
  userinfo_graph_api_wa: 0
  userinfo_graph_api_use_other_mails: 0
  userinfo_update_email: 0
  hide_email_address_warning: 0
_core:
  default_config_hash: ZTX5Ch0hlOwoqB9YJC25L-snkhhCMd2Mcv74GJMEnuY
