features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: sites/supremecourt/logo.svg
favicon:
  use_default: 1
scheme: local
header_footer_variant: default
site_name_first: 'Supreme Court of California'
site_name_second: ''
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: 'https://newsroom.courts.ca.gov/cats/California%20Supreme%20Court'
twitter: 'https://twitter.com/CaSupremeCourt'
youtube: 'https://www.youtube.com/user/CaliforniaCourts'
hide_translation: 1
header_body:
  value: 'https://jcc.granicus.com/ViewPublisher.php?view_id=50'
  format: full_html
instagram: ''
no_search_results_heading: ''
no_search_results_message:
  value: ''
  format: snippet
event_type: null
granicus_event_type: '1008'
granicus_event_details: 'https://jcc.granicus.com/ViewPublisher.php?view_id=50'
granicus_status_override: 0
granicus_events_api: 'https://jcc.granicus.com/ViewPublisher.php?view_id=50'
