_core:
  default_config_hash: gDQMni_lFzJrG9l-iw6safe7bOgRNR2942BAGxASYME
icon_base_uri: 'public://media-icons/generic'
iframe_domain: ''
oembed_providers_url: 'https://oembed.com/providers.json'
standalone_url: true
recursive_render_depth: '20'
