_core:
  default_config_hash: gn7GexesgNpOLX119r4UW6gYtxAIVD3IcHn8vxMhaMY
apikey: sendgrid
test_defaults:
  to: webdev@jud.ca.gov
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: no-reply@courtinfo.ca.gov
  to_name: ''
  reply_to: ''
