features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/jcc_elevated/logo.svg
favicon:
  use_default: 1
scheme: base
header_footer_variant: default
site_name_first: 'California Courts'
site_name_second: 'Language Access Services'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_translation: 0
hide_was_this_helpful: 1
show_google_translate: 0
no_search_results_heading: 'We are unable to find a result for you.'
no_search_results_message:
  value: "<p>Please try again with a different keyword or here are some resources that can help answer common questions:</p>\r\n\r\n<ul>\r\n\t<li>See the <a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"afdb6aca-ee83-4d68-be80-eb3a84d32e36\" href=\"/node/1\">homepage</a> for more options</li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"50f5db43-4279-41ec-877d-3ae5790d8040\" href=\"/node/89\">Become a court interpreter</a></li>\r\n\t<li>Find <a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"dedd0425-f410-4611-a990-a8543cbeee2a\" href=\"/node/44\">Court Interpreter Resources</a></li>\r\n\t<li>Find <a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"c5c82e90-ece8-4396-a62b-d3fc2c2eef6c\" href=\"/node/4\">Language Access Resources</a></li>\r\n\t<li>Self-represented litigants can find information on legal matters by visiting the <a href=\"https://selfhelp.courts.ca.gov/\">Self Help Guide</a>, including content in different languages</li>\r\n</ul>\r\n"
  format: snippet
news_default_seal: themes/custom/jcc_elevated/images/news-default-seal.svg
