features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
scheme: base
header_footer_variant: default
site_name_first: 'California Courts'
site_name_second: 'Judicial & Executive Education'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://courts.ca.gov'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_was_this_helpful: 1
hide_translation: 0
show_google_translate: 0
no_search_results_heading: ''
no_search_results_message:
  value: ''
  format: snippet
news_default_seal: ''
block_search_engine_indexing: 1
landing_advisory_body: ''
landing_course: /node/19
landing_event: ''
landing_facilities: ''
landing_job: ''
landing_bio_current: ''
landing_bio_former: ''
landing_location: ''
landing_news: ''
landing_opinion_citings_archive: ''
landing_opinion_published: ''
landing_opinion_published_extended: ''
landing_opinion_published_review_granted: ''
landing_opinion_unpublished: ''
landing_opinion_unpublished_review_granted: ''
landing_publication: ''
landing_request: ''
landing_surplus_materials: ''
