bundle: jcc_tc2
excluded:
  - encrypt.profile.tfa
  - language.content_settings.contact_message.feedback
  - language.entity.en
  - language.entity.es
  - language.entity.und
  - language.entity.zxx
  - language.mappings
  - language.negotiation
  - webform.webform.was_this_helpful
required: true
