bundle: jcc_tc2
excluded:
  - encrypt.profile.tfa
  - language.content_settings.contact_message.feedback
  - language.content_settings.contact_message.personal
  - language.entity.en
  - language.entity.es
  - language.entity.und
  - language.entity.zxx
  - language.mappings
  - language.negotiation
  - system.action.user_add_role_action.contributor
  - system.action.user_remove_role_action.contributor
  - system.action.user_add_role_action.author
  - system.action.user_remove_role_action.author
  - system.action.user_add_role_action.editor
  - system.action.user_add_role_action.manager
  - system.action.user_remove_role_action.editor
  - system.action.user_remove_role_action.manager
  - system.action.taxonomy_term_unpublish_action
  - system.action.user_add_role_action.administrator
  - system.action.user_add_role_action.legal_files
  - system.action.user_add_role_action.translator
  - system.action.user_remove_role_action.administrator
  - system.action.user_remove_role_action.legal_files
  - system.action.user_remove_role_action.translator
  - user.role.contributor
  - user.role.author
  - user.role.editor
  - user.role.manager
  - user.role.legal_files
  - user.role.translator
  - user.role.administrator
  - user.role.anonymous
  - user.role.authenticated
required: true
