name: 'All Immutable Config'
description: 'All config that will not change from site to site.'
type: module
core_version_requirement: '^9.4 || ^10'
dependencies:
  - 'access_unpublished:access_unpublished'
  - 'address:address'
  - 'admin_toolbar:admin_toolbar_tools'
  - 'allowed_formats:allowed_formats'
  - 'autocomplete_deluxe:autocomplete_deluxe'
  - 'better_exposed_filters:better_exposed_filters'
  - 'block_field:block_field'
  - 'captcha:captcha'
  - 'chosen:chosen'
  - 'colorbox:colorbox'
  - 'colorbox_inline:colorbox_inline'
  - 'components:components'
  - 'config_ignore:config_ignore'
  - 'config_split:config_split'
  - 'content_moderation_notifications:content_moderation_notifications'
  - 'crop:crop'
  - 'cshs:cshs'
  - 'ctools:ctools'
  - 'diff:diff'
  - 'drupal:automated_cron'
  - 'drupal:ban'
  - 'drupal:block'
  - 'drupal:block_content'
  - 'drupal:bulk_ban'
  - 'drupal:ckeditor'
  - 'drupal:config_translation'
  - 'drupal:contact'
  - 'drupal:content_moderation'
  - 'drupal:content_translation'
  - 'drupal:contextual'
  - 'drupal:datetime'
  - 'drupal:datetime_range'
  - 'drupal:dblog'
  - 'drupal:editor'
  - 'drupal:field'
  - 'drupal:field_ui'
  - 'drupal:file'
  - 'drupal:filter'
  - 'drupal:image'
  - 'drupal:language'
  - 'drupal:link'
  - 'drupal:locale'
  - 'drupal:media'
  - 'drupal:media_library'
  - 'drupal:menu_link_content'
  - 'drupal:menu_ui'
  - 'drupal:node'
  - 'drupal:options'
  - 'drupal:path'
  - 'drupal:path_alias'
  - 'drupal:protected_pages'
  - 'drupal:rdf'
  - 'drupal:rebuild_cache_access'
  - 'drupal:redis'
  - 'drupal:rest'
  - 'drupal:serialization'
  - 'drupal:system'
  - 'drupal:taxonomy'
  - 'drupal:telephone'
  - 'drupal:text'
  - 'drupal:toolbar'
  - 'drupal:tour'
  - 'drupal:update'
  - 'drupal:user'
  - 'drupal:views'
  - 'drupal:views_ui'
  - 'drupal:workflows'
  - 'easy_breadcrumb:easy_breadcrumb'
  - 'email_registration:email_registration'
  - 'embed:embed'
  - 'emptyparagraphkiller:emptyparagraphkiller'
  - 'encrypt:encrypt'
  - 'entity:entity'
  - 'entity_browser:entity_browser'
  - 'entity_browser:entity_browser_entity_form'
  - 'entity_embed:entity_embed'
  - 'entity_print:entity_print'
  - 'entity_reference_revisions:entity_reference_revisions'
  - 'entity_usage:entity_usage'
  - 'environment_indicator:environment_indicator'
  - 'extlink:extlink'
  - 'facets:facets'
  - 'features:features'
  - 'field_group:field_group'
  - 'file_replace:file_replace'
  - 'filefield_paths:filefield_paths'
  - 'focal_point:focal_point'
  - 'fullcalendar_view:fullcalendar_view'
  - 'geocoder:geocoder'
  - 'geocoder:geocoder_field'
  - 'geolocation:geolocation'
  - 'geolocation:geolocation_leaflet'
  - 'glossify:glossify_taxonomy'
  - 'google_tag:google_tag'
  - 'honeypot:honeypot'
  - 'image_widget_crop:image_widget_crop'
  - 'jcc_courtyard_icons:jcc_courtyard_icons'
  - 'jcc_custom:jcc_custom'
  - 'jcc_messaging_center:jcc_messaging_center'
  - 'jcc_migrate_source_ui:jcc_migrate_source_ui'
  - 'link_attributes:link_attributes'
  - 'linkit:linkit'
  - 'linkit_field:linkit_field'
  - 'mailsystem:mailsystem'
  - 'maxlength:maxlength'
  - 'media_boxcast:media_boxcast'
  - 'media_entity_download:media_entity_download'
  - 'media_file_delete:media_file_delete'
  - 'media_text:media_text'
  - 'menu_admin_per_menu:menu_admin_per_menu'
  - 'metatag:metatag'
  - 'migrate_conditions:migrate_conditions'
  - 'migrate_plus:migrate_plus'
  - 'mimemail:mimemail'
  - 'moderated_content_bulk_publish:moderated_content_bulk_publish'
  - 'module_filter:module_filter'
  - 'nodeaccess:nodeaccess'
  - 'oembed_providers:oembed_providers'
  - 'office_hours:office_hours'
  - 'openid_connect:openid_connect'
  - 'pantheon_advanced_page_cache:pantheon_advanced_page_cache'
  - 'paragraphs:paragraphs'
  - 'paragraphs_inline_entity_form:paragraphs_inline_entity_form'
  - 'paragraphs_library:paragraphs_library'
  - 'password_policy:password_policy'
  - 'pathauto:pathauto'
  - 'range:range'
  - 'real_aes:real_aes'
  - 'redirect:redirect'
  - 'robotstxt:robotstxt'
  - 'role_delegation:role_delegation'
  - 'scheduler:scheduler'
  - 'scheduler_content_moderation_integration:scheduler_content_moderation_integration'
  - 'search_api:search_api'
  - 'search_api:search_api_db'
  - 'search_api_attachments:search_api_attachments'
  - 'search_api_autocomplete:search_api_autocomplete'
  - 'search_api_exclude:search_api_exclude'
  - 'search_api_pantheon:search_api_pantheon'
  - 'search_api_solr:search_api_solr'
  - 'selective_better_exposed_filters:selective_better_exposed_filters'
  - 'sendgrid_integration:sendgrid_integration'
  - 'shs:shs'
  - 'sitemap:sitemap'
  - 'svg_image:svg_image'
  - 'tmgmt:tmgmt'
  - 'tmgmt:tmgmt_content'
  - 'tmgmt:tmgmt_file'
  - 'tooltip:tooltip'
  - 'userprotect:userprotect'
  - 'video_embed_field:video_embed_field'
  - 'video_embed_field:video_embed_media'
  - 'views_tree:views_tree'
  - 'viewsreference:viewsreference'
  - 'webform:webform'
  - 'webform_translation_permissions:webform_translation_permissions'
  - 'webform_views:webform_views'
  - 'weight:weight'
  - 'xlsx:xlsx'
  - 'xmlsitemap:xmlsitemap'
package: 'JCC TC2'
