_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  access_unpublished: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  anchor_link: 0
  autocomplete_deluxe: 0
  automated_cron: 0
  ban: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  bulk_ban: 0
  captcha: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor_a11ychecker: 0
  ckeditor_balloonpanel: 0
  ckeditor_bidi: 0
  color: 0
  colorbox: 0
  colorbox_inline: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  config_update: 0
  contact: 0
  content_lock: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  crop: 0
  cshs: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  emptyparagraphkiller: 0
  encrypt: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_print: 0
  entity_reference_facet_link: 0
  entity_reference_revisions: 0
  entity_usage: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  facets: 0
  facets_summary: 0
  features: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_delete: 0
  file_replace: 0
  filefield_paths: 0
  filter: 0
  focal_point: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geolocation: 0
  geolocation_leaflet: 0
  glossify: 0
  glossify_taxonomy: 0
  google_tag: 0
  help: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jcc_bulk_document_importer: 0
  jcc_components_variants: 0
  jcc_courtyard_icons: 0
  jcc_custom: 0
  jcc_migrate_source_ui: 0
  jcc_tc2_all_immutable_config: 0
  jcc_tc_migration: 0
  jcc_twig: 0
  jquery_ui: 0
  jcc_video_embed_akamai: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  key: 0
  language: 0
  link: 0
  link_attributes: 0
  linkit: 0
  linkit_field: 0
  linkit_media_library: 0
  locale: 0
  login_emailusername: 0
  mailsystem: 0
  maxlength: 0
  media: 0
  media_boxcast: 0
  media_entity_download: 0
  media_entity_file_replace: 0
  media_file_delete: 0
  media_file_delete_entity_usage: 0
  media_library: 0
  media_library_form_element: 0
  media_revisions_ui: 0
  media_text: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_verification: 0
  migrate: 0
  migrate_conditions: 0
  migrate_google_sheets: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  mimemail: 0
  moderated_content_bulk_publish: 0
  module_filter: 0
  mysql: 0
  node: 0
  nodeaccess: 0
  oembed_providers: 0
  office_hours: 0
  openid_connect: 0
  openid_connect_windows_aad: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  paragraphs_inline_entity_form: 0
  paragraphs_library: 0
  password_policy: 0
  password_policy_character_types: 0
  password_policy_length: 0
  password_policy_username: 0
  path: 0
  path_alias: 0
  protected_pages: 0
  range: 0
  rdf: 0
  real_aes: 0
  rebuild_cache_access: 0
  recaptcha: 0
  redirect: 0
  redis: 0
  responsive_image: 0
  rest: 0
  robotstxt: 0
  role_delegation: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search_api: 0
  search_api_attachments: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_exclude: 0
  search_api_pantheon: 0
  search_api_pantheon_admin: 0
  search_api_solr: 0
  sendgrid_integration: 0
  serialization: 0
  shs: 0
  straw: 0
  svg_formatter: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  tmgmt: 0
  tmgmt_content: 0
  tmgmt_file: 0
  token: 0
  toolbar: 0
  tooltip: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  userprotect: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_ui: 0
  viewsreference: 0
  views_tree: 0
  webform: 0
  webform_attachment: 0
  webform_entity_print: 0
  webform_entity_print_attachment: 0
  webform_spam_words: 0
  webform_translation_permissions: 0
  webform_ui: 0
  webform_views: 0
  weight: 0
  workflows: 0
  xlsx: 0
  extlink: 1
  menu_admin_per_menu: 1
  pathauto: 1
  selective_better_exposed_filters: 0
  xmlsitemap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  jcc_components_profile: 1000
  jcc_messaging_center: 10
  email_registration: 0
theme:
  claro: 0
  stable: 0
  gin: 0
  jcc_components: 0
  jcc_elevated: 0
  jcc_storybook: 0
profile: jcc_components_profile
